FROM node:22 AS ui-build

ARG PUBLIC_UI_URL
ARG API_URL
ARG SOCKET_URL

ENV PUBLIC_UI_URL=${PUBLIC_UI_URL}
ENV API_URL=${API_URL}
ENV SOCKET_URL=${SOCKET_URL}
ENV NODE_OPTIONS=--max-old-space-size=4096

WORKDIR /app

COPY ./src/ui /app
COPY ./src/shared/ts /shared/ts

RUN cd /shared/ts && yarn install && yarn run build && yarn link
RUN yarn config set registry "http://registry.npmjs.org"
RUN cd /app && yarn install --network-timeout 100000 && yarn build

FROM nginx:latest

COPY ./docker/nginx.dokploy.conf.template /etc/nginx/templates/default.conf.template
COPY ./docker/server/nginx.conf /etc/nginx/nginx.conf
COPY --from=ui-build /app/dist /usr/share/nginx/html

CMD ["nginx-debug", "-g", "daemon off;"]
